// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hmqrtiijlvbjnnspumly.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhtcXJ0aWlqbHZiam5uc3B1bWx5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NTM1MzgsImV4cCI6MjA2NTMyOTUzOH0.OmQRfpQ1mtjYj3mL7ta5mwmOHG8YGTKH0OITPDwnGBs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);