// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kiictjbrvfujhjivdoiq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpaWN0amJydmZ1amhqaXZkb2lxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2ODg4NjksImV4cCI6MjA2NTI2NDg2OX0.gsV7TjHKWVkHtzbMmGi8xvkLFcaXkbb2Z9d5R4h7IzI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);